//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Html {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Html() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Report.Html", typeof(Html).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;
        ///				
        ///.datatable {
        ///border: 1px solid black;
        ///}
        ///#overallExecution ,#overallExecution th,#overallExecution td {
        ///	border: 1px solid black;
        ///}
        ///
        ///#testTable, #searchInput {
        ///  border-collapse: collapse; /* Collapse borders */
        ///  width: 100%; /* Full-width */
        ///  border: 1px solid #ddd; /* Add a grey border */
        ///  font-size: 18px; /* Increase font-size */
        ///}
        ///
        ///#testTable th, #testTable td, #searchInput th, #searchInput td {
        ///  text-align: left; /* Left-align text */
        ///  padding: 12px; /* Add padding */ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSS {
            get {
                return ResourceManager.GetString("CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Automation Framework Report&lt;/title&gt;
        ///&lt;/head&gt;.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;
        ///
        ///function searchFeature() {
        ///  // Declare variables 
        ///  var input, filter, table, tr, td, i, txtValue;
        ///  input = document.getElementById(&quot;featureSearch&quot;);
        ///  filter = input.value.toUpperCase();
        ///  table = document.getElementById(&quot;testTable&quot;);
        ///  tr = table.getElementsByTagName(&quot;tr&quot;);
        ///
        ///  // Loop through all table rows, and hide those who don&apos;t match the search query
        ///  for (i = 0; i &lt; tr.length; i++) {
        ///    td = tr[i].getElementsByClassName(&quot;feature&quot;)[0];
        ///    if (td) {
        ///      txtValue = td.tex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scripts {
            get {
                return ResourceManager.GetString("scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;
        ///&lt;table id=&quot;searchInput&quot;&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;&lt;input type=&quot;text&quot; id=&quot;featureSearch&quot; onkeyup=&quot;searchFeature()&quot; placeholder=&quot;Search for Feature...&quot;&gt;&lt;/td&gt;
        ///&lt;td&gt;&lt;input type=&quot;text&quot; id=&quot;scenarioSearch&quot; onkeyup=&quot;searchScenario()&quot; placeholder=&quot;Search for Scenario...&quot;&gt;&lt;/td&gt;
        ///&lt;td&gt;&lt;input type=&quot;text&quot; id=&quot;resultSearch&quot; onkeyup=&quot;searchResult()&quot; placeholder=&quot;Search for Result...&quot;&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;br&gt;.
        /// </summary>
        internal static string SearchInput {
            get {
                return ResourceManager.GetString("SearchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table id=&quot;testTable&quot;&gt;
        ///&lt;tr class=&quot;header&quot;&gt;
        ///&lt;th&gt;Feature&lt;/th&gt;
        ///&lt;th&gt;Scenario&lt;/th&gt;
        ///&lt;th&gt;Steps&lt;/th&gt;
        ///&lt;th&gt;Error Message&lt;/th&gt;
        ///&lt;th&gt;Result&lt;/th&gt;
        ///&lt;th&gt;Execution Time&lt;/th&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string TestTableHeader {
            get {
                return ResourceManager.GetString("TestTableHeader", resourceCulture);
            }
        }
    }
}
