//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Html {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Html() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Report.Html", typeof(Html).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;style&gt;
        ///#overallExecution ,#overallExecution th,#overallExecution td {
        ///	border: 1px solid black;
        ///}
        ///
        ///#testTable, #searchInput {
        ///  border-collapse: collapse; /* Collapse borders */
        ///  width: 100%; /* Full-width */
        ///  border: 1px solid #ddd; /* Add a grey border */
        ///  font-size: 18px; /* Increase font-size */
        ///}
        ///
        ///#testTable th, #testTable td, #searchInput th, #searchInput td {
        ///  text-align: left; /* Left-align text */
        ///  padding: 12px; /* Add padding */
        ///}
        ///
        ///#testTable tr, #searchInput tr {
        ///  /* Add [stringa troncata]&quot;;.
        /// </summary>
        internal static string CSS {
            get {
                return ResourceManager.GetString("CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Automation Framework Report&lt;/title&gt;
        ///&lt;/head&gt;.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;script&gt;
        ///
        ///function searchFeature() {
        ///  // Declare variables 
        ///  var input, filter, table, tr, td, i, txtValue;
        ///  input = document.getElementById(&quot;featureSearch&quot;);
        ///  filter = input.value.toUpperCase();
        ///  table = document.getElementById(&quot;testTable&quot;);
        ///  tr = table.getElementsByTagName(&quot;tr&quot;);
        ///
        ///  // Loop through all table rows, and hide those who don&apos;t match the search query
        ///  for (i = 0; i &lt; tr.length; i++) {
        ///    td = tr[i].getElementsByClassName(&quot;feature&quot;)[0];
        ///    if (td) {
        ///      txtValue = td.tex [stringa troncata]&quot;;.
        /// </summary>
        internal static string scripts {
            get {
                return ResourceManager.GetString("scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;br&gt;
        ///&lt;table id=&quot;searchInput&quot;&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;&lt;input type=&quot;text&quot; id=&quot;featureSearch&quot; onkeyup=&quot;searchFeature()&quot; placeholder=&quot;Search for Feature...&quot;&gt;&lt;/td&gt;
        ///&lt;td&gt;&lt;input type=&quot;text&quot; id=&quot;scenarioSearch&quot; onkeyup=&quot;searchScenario()&quot; placeholder=&quot;Search for Scenario...&quot;&gt;&lt;/td&gt;
        ///&lt;td&gt;&lt;input type=&quot;text&quot; id=&quot;resultSearch&quot; onkeyup=&quot;searchResult()&quot; placeholder=&quot;Search for Result...&quot;&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;br&gt;.
        /// </summary>
        internal static string SearchInput {
            get {
                return ResourceManager.GetString("SearchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;table id=&quot;testTable&quot;&gt;
        ///&lt;tr class=&quot;header&quot;&gt;
        ///&lt;th&gt;Feature&lt;/th&gt;
        ///&lt;th&gt;Scenario&lt;/th&gt;
        ///&lt;th&gt;Steps&lt;/th&gt;
        ///&lt;th&gt;Error Message&lt;/th&gt;
        ///&lt;th&gt;Result&lt;/th&gt;
        ///&lt;th&gt;Execution Time&lt;/th&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string TestTableHeader {
            get {
                return ResourceManager.GetString("TestTableHeader", resourceCulture);
            }
        }
    }
}
